### PR TITLE
Add a .travis.yml. Fixes #71

### LINKED ISSUE #71: Travis up for testing that Jekyll builds fine
Get Travis in place for basic stuff.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
I'd like it if someone could activate travis so I can verify that this works.

**Comment by konklone** [comment]
I've updated the `.travis.yml` to model it after [the one we use for 18f.gsa.gov](https://github.com/18F/18f.gsa.gov/blob/staging/.travis.yml). I've also enabled Travis CI for the repo. It's building as I speak!

**Comment by alex** [comment]
Failing, looks like because it's trying to build a sample post, is this because we don't have our own `_posts` directory?

**Comment by konklone** [comment]
Fixed, and passed. :+1:

**Pull request merged**
