### PR TITLE
A page on Certificates

### PR DESCRIPTION
**Pull request by konklone**
This pull request adds a page dedicated to `Certificates`, structured as an FAQ to address many of the issues that have come up in the federal community. This is more government-oriented than some of the other resources pages.

It includes an introduction to certificates and CAs, a description of the federal PKI, a discussion about how CAs are overseen (the CA/Browser Forum), a summary of (the lack of) federal requirements restricting CA use, and some ways in which domain owners _can_ monitor or restrain the use of certs from non-approved or unexpected CAs.

The proposed page can be viewed most easily in GitHub here:

https://github.com/GSA/https/blob/certificates/pages/certificates.md

I also added the open-source [crt.sh](https://crt.sh) to the Resources page. I also took the Table of Contents model I used for the Technical Guidelines page and the new Certificates page and added it to the general FAQ page.

There's still a bit I want to add before merging:

- [x] `What kind of certificate should I get for my domain?` (establishing that DV is fine, that short-lived certificates are fine, maybe mentioning other stuff)

### CODE REVIEW

**Comment by konklone** [comment]
I've added a section about certificate choices, and am done here -- this PR is ready for feedback and merging.

**Comment by gbinal** [comment]
:+1:

**Comment by dnesting** [comment]
This is great background information.  The only comment I have is that the description says it's "guidance" but the page seems more about providing background information and not guidance.  Is that the goal of this page?

**Comment by konklone** [comment]
@dnesting I just updated the description to be closer to what the page says at the top. I think parts of the FAQ are effectively guidance, but yeah, it's more precisely described as FAQ/background.

**Comment by konklone** [comment]
Reposting @jmfenton's comment from #151 to move it here:

> A few miscellaneous comments on the new certificates.md page:
> 
> * The signature from the CA vouches for the relationship between the public (not private) key and the authorized... since that's what the CA has to sign.
> * Under "technical information" contained in the certificate, it would be good to list algorithms as well since there is discussion later about use of SHA1.
> * It vouches for hostname(s), not domain(s), since certificates (except wildcards) are valid for specific hosts, not the whole domain (even though it's validated by domain).
> * "CA it trusts has decided to trust the website" overstates what the CA is trusting, since it hasn't even looked at the website.  It trusts that the website is controlled by an authorized party.
> * Some quantification of what is meant by "shorter lived" might be useful. Are we talking about days or years?
> * I wince a little at RFC 6962 being called "the official standard" since it's an experimental RFC. IETF has a big problem with people calling anything with an RFC number a "standard", and hate to see that perpetuated.

**Comment by konklone** [comment]
From #150:

> in certificates.md, ANSSI is mis-spelled (2 places).

**Comment by konklone** [comment]
@jimfenton --

> in certificates.md, ANSSI is mis-spelled (2 places).

I fixed this in 19ccbce, thank you for pointing it out.

> A few miscellaneous comments on the new certificates.md page:

I addressed these in 6cbd9af, as described below.

> * The signature from the CA vouches for the relationship between the public (not private) key and the authorized... since that's what the CA has to sign.

I changed it to "keypair". The CA is signing the public key, but since that's mathematically tied to the private key, it's vouching for both of them. The private key is more important than the public key in this regard, since anyone can own a copy of the public key, but only the private key's owner is authorized.

> * Under "technical information" contained in the certificate, it would be good to list algorithms as well since there is discussion later about use of SHA1.

:+1: I added "what algorithm the CA used to sign it" to the bullet.

> * It vouches for hostname(s), not domain(s), since certificates (except wildcards) are valid for specific hosts, not the whole domain (even though it's validated by domain).

This is a tricky one. I understand that hostname is less precise than domain in this case, but I also think that hostname isn't as well-understood a term among this page's intended audience. By "domain" I mean "domain or subdomain", but it's also clunky to constantly refer to both. I'm inclined to leave it as it is unless it's demonstrably causing confusion.

> * "CA it trusts has decided to trust the website" overstates what the CA is trusting, since it hasn't even looked at the website.  It trusts that the website is controlled by an authorized party.

Good call -- I simplified it to "...CA it trusts has decided to trust the information in the certificate."

> * Some quantification of what is meant by "shorter lived" might be useful. Are we talking about days or years?

Well, a shorter-lived cert would usually be days or months, but I'm also not trying to draw a line in the sand or point to a specific timeframe. I'm not sure what current CA availability is for days- or months-long certificates, and don't wish to point agencies too strongly at a specific vendor or set of vendors. The general concept of "short is better than long" is the idea (which I think many find counter-intuitive) I want to communicate.

> * I wince a little at RFC 6962 being called "the official standard" since it's an experimental RFC. IETF has a big problem with people calling anything with an RFC number a "standard", and hate to see that perpetuated.

I reworded it to "the experimental standard" instead. For better or worse, RFC 6962 is the standard describing CT. I know another RFC is in the works that will iterate on it, and then that one will replace it as the standard. I don't know how else I would describe the relationship RFC 6962 has to CT right now.

Those were very helpful comments @jimfenton, more welcome any time!

**Comment by konklone** [comment]
OK, I've merged the PR and the material is on https://https.cio.gov/certificates/

If there are any more issues with it, we can definitely keep changing it, it's a living site. Thanks to everyone who rang in with comments on and off GitHub

**Comment by jimfenton** [comment]
A little late responding, but I'm still having trouble with the domain name vs. hostname thing.  Really, the intended audience of this document doesn't know what a hostname is?

The important thing is that they understand that if they're getting a certificate for https://mumble.gsa.gov/, the certificate needs to be valid for mumble.gsa.gov, the certificate needs to be issued for mumble.gsa.gov, not gsa.gov. It's not a domain, not a subdomain.  Perhaps call it the "website name" if hostname doesn't register.

Of course, they're going to get confused anyway since the certificate calls it the Common Name (CN), and nobody uses that terminology.

**Comment by konklone** [comment]
> A little late responding, but I'm still having trouble with the domain name vs. hostname thing. Really, the intended audience of this document doesn't know what a hostname is?

Unfortunately, correct. It's important that the page be as understandable as possible to web managers, contractors, vendors, and government SES folks of all stripes, not just web developers and people already familiar with internet mechanics.

I'm not totally unpersuadable on it, but I'd prefer to first attempt a solution that emphasizes "domains/subdomains" rather than hostnames.

**Pull request merged**
