### PR TITLE
A compliance guide FAQ answer about the use of federal certificates (e.g. FPKI and DoD)

### PR DESCRIPTION
**Pull request by konklone**
This attempts to answer a commonly asked question about the use of federally issued certificates from enterprise CAs, such as the Federal PKI, Department of Defense, and other agency-operated CAs.

For context: M-15-13 isn't attempting to set policies around which CAs are appropriate to use and when. M-15-13 also doesn't require the use of any particular protocols or ciphers. M-15-13 cares only about ensuring that users of federal web services have the protections of confidentiality, authenticity, and integrity at all times. 

To that end, M-15-13's sole practical requirement for federal sites [is very simple](https://https.cio.gov/#guidelines):

_* Agencies must make all existing websites and services accessible through a secure connection (HTTPS-only, with HSTS) by December 31, 2016._

This proposed compliance FAQ answer makes clear that any CA, commercial or federal, is fine for use, consistent with our guidance on the [Certificates page](https://https.cio.gov/certificates/#are-there-federal-restrictions-on-acceptable-certificate-authorities-to-use?). 

However, the requirement to use [HSTS](https://https.cio.gov/hsts/) does introduce a practical difficulty in using federally issued certificates when a website's users can't be fully expected to have that root installed, because HSTS disables the ability for users to click through certificate warnings in supporting browsers. 

This answer describes that, and says that, practically speaking, an agency will need to separate the web services the public uses from those used by communities which consistently trust federal roots (generally this means a government-internal audience). Because [the US government does not run a publicly trusted certificate authority](/certificates/#does-the-us-government-operate-a-publicly-trusted-certificate-authority?), web services that see use by the general public are, in practice, likely to need a certificate from a publicly trusted (commercial) certificate authority.

It's worth acknowledging here that this guidance, while a straightforward outcome of M-15-13 and solidly in line with industry-wide security best practices, conflicts with practices used by some federal agencies today, particularly the Department of Defense. 

Nonetheless, OMB should adopt this answer as part of their guidance, so as to resolve any confusion around M-15-13's requirements and scope, and to meet the policy's goals of ensuring the security of federal web services for their users among the public and among the federal workforce.

In any case, feedback and discussion on this proposed answer would be very welcome. Screenshot of the rendered answer below:

image

### CODE REVIEW

**Comment by konklone** [comment]
Note that this doesn't yet explicitly address the topic of how to offer root certificates for download to users. I don't think that it should get into _whether_ agencies should engage in this practice, since this is an OMB Compliance Guide and I think that is outside the scope of M-15-13's requirements -- but it might be worth explicitly saying that _if_ this is done, the root certificate should be served securely as well. Which, in practice, means that federal root certificates would need to be served using HTTPS guaranteed by commercial certificates.

**Comment by alex** [comment]
I don't love adding text like that, since to me it implies there's a
possibility that's ok, which in my view there isn't.

On Thu, Mar 24, 2016 at 9:17 PM, Eric Mill <notifications@github.com> wrote:

> Note that this doesn't yet explicitly address the topic of how to offer
> root certificates for download to users. I don't think that it should get
> into *whether* agencies should engage in this practice, since this is an
> OMB Compliance Guide and I think that is outside the scope of M-15-13's
> requirements -- but it might be worth explicitly saying that *if* this is
> done, the root certificate should be served securely as well. Which, in
> practice, means that federal root certificates would need to be served
> using HTTPS guaranteed by commercial certificates.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/https/pull/188#issuecomment-201093209>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by konklone** [comment]
cc @lachellel @grandamp as well

**Comment by grandamp** [comment]
To me, I believe it depends on the use case.  Federally issued certificates are honored by the browsers.  I.e., https://github.com/18F/fpki-testing/issues

The Common Policy Root CA "SHOULD" be used as the trust anchor, which is also distributed by Microsoft.  But, clearly other paths can be relied on (even with revoked intermediate CAs)!

Federal Agencies typically trust the Common Policy Root CA on Microsoft assets, and other assets, in support of "network/smart card login", yet the milage may vary.

If an agency wants to issue FPKI certs to a web server, where the user community is " government" only, then I don't understand how that is a bad thing.

**Comment by konklone** [comment]
> If an agency wants to issue FPKI certs to a web server, where the user community is " government" only, then I don't understand how that is a bad thing.

It's absolutely not a bad thing, and that's exactly what the text in this pull request is trying to say.

It's also trying to say that if the audience is *not* government-only, then in practice they will need to use a commercially issued certificate. In other words, pages like https://www.iad.gov/Cira/warnings.cfm should never need to exist.

**Comment by pzb** [comment]
You are presenting FPKI or Internet PKI as an either-or situation.  An agency could set up an issuing CA which is signed/cross-signed by both the Federal PKI and a commercial Internet PKI CA to allow certificates to be trusted by customers who trust either set.  It would require some trickery to send both chains, but I think it can be done in a way compatible with the vast majority of clients.  It would also require that Issuing CA to have a CPS that complies with both the FPKI CP and commercial root program requirements, but I think it is doable.

**Comment by lachellel** [comment]
@pzb I wouldn't even suggest that as an option  ... it's complex enough as is to explain and to implement and manage and audit and... _insert everything and anything about explaining PKI or even PK_  

in the here and now: if we present what it looks like Today and what an implementer has to consider for a decision, we can reduce the confusion hopefully.

**Comment by jsha** [comment]
LGTM

**Comment by lachellel** [comment]
@konklone I noticed we haven't merged this content yet.  Do we want to ask for more feedback?

@weirdscience did you / can you take a look at this other change being proposed?  I think this is the intersection with #189

**Pull request merged**
