### PR TITLE
Added a paragraph on TLS_FALLBACK_SCSV. Refs #22

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by dstufft** [comment]
Do you want to mention that all services *should* be deployed in a way to ensure that they get ``TLS_FALLBACK_SCSV`` enabled? It's not nearly as important as other things but realistically people should be shooting for it to be there and be on.

**Comment by alex** [comment]
@dstufft meaning adding a fragment like, "This option can be enabled on all servers without any drawbacks"?

**Comment by dstufft** [comment]
I'm thinking more like *SHOULD* be enabled on all servers, though I don't feel super strongly about it.

**Comment by alex** [comment]
@dstufft done!

**Comment by dstufft** [comment]
:ship:

**Comment by konklone** [comment]
I reworded it a bit. :+1: from me. @alex, feel free to merge if you're good with my rewording.

**Pull request merged**
