### PR TITLE
Add HSTS header example for the Caddy server

### PR DESCRIPTION
**Pull request by adelevie**
Synthesizes info from https://caddyserver.com/docs/header.

### CODE REVIEW

**Comment by alex** [comment]
Caddy is extremely uncommon (IME) compared to nginx, apache, and IIS. @konklone, do we want this to be a universal reference, or just handle the common cases?

**Comment by konklone** [comment]
@adelevie I generally agree with @alex's point -- is there a good link for this? If so, let's add a bullet to the `Resources` list just below this that links to other server instructions, which for now will just be Caddy. Sound okay?

**Comment by alex** [comment]
Should have led with this -- thanks for contributing!

**Comment by adelevie** [comment]
There is no good link for this.

Of course, a few more minutes of Googling would lead many people to [general Caddy docs](https://caddyserver.com/docs/header) on setting headers. But having the directive fully spelled out would be nice for many folks who shy away from these things (like me!).

I could think about finding a better place to post this snippet, but as of now, there is no good place specifying how to set the HSTS header on Caddy.

**Comment by konklone** [comment]
I added a couple commits that incorporate your work but modify it to a list of a few less common web servers and how to add custom headers to them: https://https.cio.gov/hsts/

image

The goal is to be an easy reference point for other servers, without having to maintain up-to-date instructions on how to do it in every single web server someone might use.

Further feedback/PRs welcome!

**Pull request merged**
