### PR TITLE
Design overhaul to use US Web Design Standards

### PR DESCRIPTION
**Pull request by konklone**
This pull request is a long-overdue visual overhaul for https.cio.gov, which:

* Uses the US Web Design Standards
* Matches the theme of `cyber.dhs.gov` and `itmodernization.cio.gov`
* Has a sticky sidebar
* Works way better on mobile

Main page:

screenshot from 2017-10-21 20-34-17

And a shot of a scrolled-down page, with sticky header as well as the rendering for `<code>` and `<pre>` sections:

screenshot from 2017-10-21 20-35-31

cc @hmft @gbinal

### CODE REVIEW

**Comment by konklone** [comment]
I also removed the Travis build file, as we no longer use Travis and I'm not yet certain how to replicate the auto-deploy setup in Circle. I think auto-deployment is likely best done by moving to Federalist, anyhow (the site is still, for now, deployed directly via cloud.gov).

**Comment by rustypickens** [comment]
Looks great, Eric! Very well organized and easy to access. Great work.

**Comment by gbinal** [comment]
Looks great!  Glad to utilize the design standards.  

Let's do this.

**Comment by konklone** [comment]
Thanks, all! Also, another measure of the USWDS' success:

screen shot 2017-10-23 at 9 22 40 am

**Comment by h-m-f-t** [comment]
Very nice! 🎉

**Pull request merged**
