### PR TITLE
Update hsts.md

### PR DESCRIPTION
**Pull request by mattbrundage**
A protocol is more accurately referred to as a "scheme" when within the context of a URI. http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

### CODE REVIEW

**Comment by konklone** [comment]
You're right, though we're targeting this page to a broader audience than just implementers. @gbinal, any thoughts on whether "protocol" or "scheme" is more/less/same desirable?

**Comment by gbinal** [comment]
I could go either way on this one.  I do think that 'protocol' is a bit more readable in this context and that the sentence is still strong in its current form.

**Comment by dnesting** [comment]
How about "protocol scheme"?

**Comment by mattbrundage** [comment]
In light of the comments so far, leaving the wording as-is would be acceptable.

**Comment by konklone** [comment]
Thanks for the contribution anyhow @mattbrundage, and please do send more our way! :+1:

**Pull request closed without merging**
