### PR TITLE
Rewrite DNSSEC sections

### PR DESCRIPTION
**Pull request by konklone**
I tried to rewrite the DNSSEC answers to be more precise and less inflammatory.

cc @NoahKunin for review.

### CODE REVIEW

**Comment by alex** [comment]
This looks about right to me. You might want to link to Thomas Ptacek's breakdown of DNSSEC: http://sockpuppet.org/blog/2015/01/15/against-dnssec/

**Comment by konklone** [comment]
@alex I thought about it, but I'm not trying to argue here that DNSSEC is bad or should be discouraged. DNSSEC is currently an OMB requirement for all federal websites, and is [tracked by NIST](http://fedv6-deployment.antd.nist.gov/cgi-bin/generate-gov). I am trying to argue that DNSSEC is insufficient to create a private, secure communication channel between client and server.

**Comment by alex** [comment]
Fair point, that's a much more relevant scoping. I think what you've got
does a good job of that.

On Sun, Mar 1, 2015 at 8:53 PM, Eric Mill <notifications@github.com> wrote:

> @alex <https://github.com/alex> I thought about it, but I'm not trying to
> argue here that DNSSEC is bad or should be discouraged. DNSSEC is currently
> an OMB requirement for all federal websites, and is tracked by NIST
> <http://fedv6-deployment.antd.nist.gov/cgi-bin/generate-gov>. I am trying
> to argue that DNSSEC is insufficient to create a private, secure
> communication channel between client and server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/https/pull/39#issuecomment-76658486>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by NoahKunin** [comment]
Very small edit, merging!

**Comment by alex** [comment]
> If HTTPS is not compromised, users receive a notable warning message from their browser that will prevent them from visiting

I think there's an extra negation here?

**Comment by NoahKunin** [comment]
@alex so maybe this, plus extra clarification:

> If HTTPS is not compromised, but the DNS is spoofed, users will receive a notable warning message from their browser. These warnings prevent users from visiting the possibly malicious site, until users overtly confirm they want to disregard the warning.

**Comment by alex** [comment]
Much clearer. Thanks!

On Thu, Mar 5, 2015 at 7:49 PM, Noah Kunin <notifications@github.com> wrote:

> @alex <https://github.com/alex> so maybe this, plus extra clarification:
>
> If HTTPS is not compromised, but the DNS is spoofed, users will receive a
> notable warning message from their browser. These warnings prevent users
> from visiting the possibly malicious site, until users overtly confirm they
> want to disregard the warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/https/pull/39#issuecomment-77485360>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by konklone** [comment]
I updated the text using a variant of this in 57c6143. The line about users overtly confirming they want to disregard the warning is not accurate in an HSTS context -- that's the (only) other thing HSTS does, is disable the ability to click through warnings.

**Comment by NoahKunin** [comment]
:+1:

**Pull request merged**
