### PR TITLE
s/privacy/confidentiality/

### PR DESCRIPTION
**Pull request by willchan**
In each case I saw privacy used, I think confidentiality is more accurate. Given the level of technical discussion in this FAQ, I think it's more appropriate to use the proper terminology.

### CODE REVIEW

**Comment by alex** [comment]
There's another privacy in the DNSSEC section if you want to get that as well.

**Comment by willchan** [comment]
Missed it the first time, thanks.

**Comment by alex** [comment]
np -- lgtm :sparkles:

**Comment by konklone** [comment]
So let's talk about this one. I intentionally used "privacy" here instead of "confidentiality", because I'm trying to appeal to a broader audience than those who might be reached by the formal description of security guarantees that HTTPS provides.

I realize it's a less precise term, and so maybe in areas where precision matters, we should stick to "confidentiality". Overall, I'd like this document to not just describe HTTPS, but to sell it.

**Comment by willchan** [comment]
Yeah, I figured that was a possibility. I guess I found the level of
technicality inconsistent. At the point when you discuss integrity and
authentication, confidentiality really seems like the right term to use.
I'm thinking that maybe we should use privacy in the memo, but in this
document, we should have a more consistent usage of precise terminology
instead. Maybe a middle ground would be to add a little wording around
these properties being necessary preconditions for user privacy?

**Comment by konklone** [comment]
Let's merge in and revise if need be later. :+1:

**Pull request merged**
